### ISSUE TITLE
Placeholders are not interpolated in workspaces when using "consolidate-commits=true"

### ISSUE THREAD

**Issue by razvan** [crate-ci/cargo-release#310] opened 2021-08-20 09:10 UTC
In my workspace the `release.toml` looks like this:
```
consolidate-commits = true
no-dev-version = false
dev-version-ext = "nightly"
pre-release-hook = ["../release/scripts/release-pre.sh"]
pre-release-commit-message = "release {{version}}"
post-release-commit-message = "prepare {{next_version}}"
disable-push = true
disable-tag = true
tag-name = "{{version}}"
disable-publish = true
```

The commit messages created look like this:
```
9026a15 2021-08-20T10:28:06+02:00 Razvan-Daniel Mihai prepare {{next_version}}
4a3607f 2021-08-20T10:28:06+02:00 Razvan-Daniel Mihai release {{version}}
```
I expected the placeholders to be interpolated with the actual version strings.

**Comment by epage** [comment] 2021-08-20 10:56
The problem is that each crate could have its own version, we there isn't a value for us to fill in with.

Over at https://github.com/sunng87/cargo-release/issues/222, we are talking about ways to mark crates as sharing a version and they would use that shared version.  

Since this is a dupe of https://github.com/sunng87/cargo-release/issues/222, going to go ahead and close this.

**Closed** 2021-08-23 13:34 UTC
