### ISSUE TITLE
Incorrect "Uncommitted changes detected"

### ISSUE THREAD

**Issue by kornelski** [crate-ci/cargo-release#416] opened 2022-02-05 23:38 UTC
`cargo release` is giving me:

> [2022-02-05T23:34:28Z ERROR cargo_release::release] Uncommitted changes detected, please commit before release.

but the repo is fine:

```bash
git status --verbose
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
```

I think it's because this project is a git submodule of a parent repository, and the parent has uncommitted changes:

```
/home/foo/.git # mess
/home/foo/Cargo.toml # workspace root
/home/foo/subdir/.git # clean
/home/foo/subdir/Cargo.toml # crate to release
cd /home/foo/subdir/; cargo release
```

In this case I do not want to commit changes in the parent git repo, it's a big work-in-progress, and I'm ready only to release one submodule of it.

**Comment by kornelski** [comment] 2022-02-05 23:45
Alternatively, it'd be nice to have `--allow-dirty` option like other cargo commands.

**Comment by epage** [comment] 2022-02-05 23:52
I believe this is a duplicate of https://github.com/crate-ci/cargo-release/issues/195

Did you run with trace-level logging?  Was there anything in the log related to this?

**Comment by kornelski** [comment] 2022-02-06 00:36
Oh, I think it may be due to to workspace. The root of the workspace is a different git repo than the folder which workspace-member crate resides.

**Comment by epage** [comment] 2022-02-06 00:41
We have https://github.com/crate-ci/cargo-release/issues/263 for submodules.  The problem is I don't use them so I have a hard time thinking of all of the cases or how all of the behavior should work out.

Since we have both #195 and #263, going to close this in favor of those.

**Closed by epage** 2022-02-06 00:41 UTC
