### ISSUE TITLE
Freeze with the sparse protocol

### ISSUE THREAD

**Issue by loyd** [crate-ci/cargo-release#692] opened 2023-08-04 17:34 UTC
I'm trying to release all crates in a workspace with the latest stable toolchain (1.71.1) and cargo-release (0.24.11) and after the `Published` step the whole process just freezes and nothing happens
```
note: Waiting for `elfo-dumper v0.2.0-alpha.5` to be available at registry `crates-io`.
You may press ctrl-c to skip waiting; the crate should be available shortly.
   Published elfo-dumper v0.2.0-alpha.5 at registry `crates-io`
```

After enabling the old protocol, it works as expected:
```
[registries.crates-io]
protocol = "git"
```

**Comment by imp** [comment] 2023-08-08 10:16
It seems that it is not a freeze, but rather long delay caused by `cargo-release` updating crates.io `git` index (which is falling behind after switch to `sparse` index by default in 1.71). Naturally if `git` index is sufficiently up-to-date the refresh doesn't take long.

Perhaps `crates-index` dependency may be updated to latest version (0.19 -> 2.1) to allow `cargo-release` to utilize `sparse` index instead?

**Comment by epage** [comment] 2023-11-01 21:06
Closing in favor of #679 (different symptom, same root cause)

**Closed by epage** 2023-11-01 21:06 UTC
