### ISSUE TITLE
Workspace releases with [patch] need different ordering

### ISSUE THREAD

**Issue by ryankurte** [crate-ci/cargo-release#213] opened 2020-05-20 02:19 UTC
Hey, I'm using workspaces with top level patch definitions. `cargo release` attempts to build and release each crate one at a time, however, as the first crate version gets bumped the publish fails as the build executes across the workspace without updating the lockfile.

I believe the correct approach here would be to apply the version bump to _all crates_, then to run `cargo update` to update the workspace lockfile, then to build/publish _all crates_. I can look into making this change, but, is this something you'd be interested in supporting?

**Comment by epage** [comment] 2020-05-20 13:41
`cargo release` should be updating the lock file after each version bump.  See https://github.com/sunng87/cargo-release/blob/master/src/main.rs#L589

So I suspect the root cause is something else and that bumping all crates first won't help (I vaguely remember it might actually break things but I could be wrong).  Do you have a repo we can reproduce on?

**Comment by jamwaffles** [comment] 2020-11-07 20:42
I think we're having the same problem with embedded-graphics. There's a repo here if you need to test stuff: https://github.com/embedded-graphics/embedded-graphics/tree/906ee1180cf31872b03aee037b9022c5fde30630

We have 4 crates: `embedded-graphics`, `embedded-graphics-simulator`, `tinytga`, `tinybmp`. The `[patch.crates-io]` section in the workspace `Cargo.toml` looks like this:

```toml
[patch.crates-io]
embedded-graphics = { path = "embedded-graphics" }
embedded-graphics-simulator = { path = "simulator" }
tinytga = { path = "tinytga" }
tinybmp = { path = "tinybmp" }
```

Dependencies look roughly like this:

- `embedded-graphics` (dev) -> `tinytga`
- `embedded-graphics-simulator` -> `embedded-graphics`
- `embedded-graphics-simulator` (dev) -> `tinybmp`
- `tinybmp` -> `embedded-graphics`
- `tinytga` -> `embedded-graphics`

We're currently splitting repos apart, so there'll be no more workspace soon after the commit the above link is pinned to, but in its current state it may help with debugging.

**Comment by epage** [comment] 2021-08-25 13:44
I think this is a duplicate of #82, closing in favor of that.  If it isn't feel free to say how this is different

**Closed by epage** 2021-08-25 13:44 UTC
